/**
 * 捨て方辞典：品目データ（SEO需要順・カテゴリ別）
 * テンプレート: 結論・処分方法3選・ふれあいの丘アドバイス・CTA
 */

export type GomiConclusion = "可燃" | "不燃" | "粗大ゴミ" | "NG";
export type CtaType = "default" | "buy_sell" | "memorial" | "difficult";

export interface DisposeItem {
  slug: string;
  name: string;
  categoryId: "memorial" | "furniture" | "appliance" | "difficult" | "hobby" | "daily";
  /** 自治体で捨てられるか（NG＝自治体回収不可） */
  gomiConclusion: GomiConclusion;
  costNote: string;
  canSell: boolean;
  sellNote?: string;
  /** A. 自治体のゴミに出す */
  methodA: string;
  /** B. 買取に出す */
  methodB: string;
  /** C. 業者に回収してもらう */
  methodC: string;
  /** ふれあいの丘からのアドバイス（独自性） */
  adviceFureai: string;
  memorialNote?: string;
  /** CTAの訴求軸: 買取強化 / 想い・供養 / 処理困難物業者マッチング */
  ctaType: CtaType;
}

export const DISPOSE_ITEMS: DisposeItem[] = [
  // --- 供養・想い出 ---
  {
    slug: "butsudan",
    name: "仏壇・仏具",
    categoryId: "memorial",
    gomiConclusion: "粗大ゴミ",
    costNote: "お焚き上げ・供養込みで1〜5万円程度。自治体の粗大ゴミでは受け付けない地域が多く、寺院・業者に依頼するのが一般的。",
    canSell: true,
    sellNote: "中古仏壇の買取は需要が限定的。状態が良ければ買取店やリユース店に相談を。",
    methodA: "自治体によっては「仏壇」を粗大ゴミで受け付けるが、多くの地域では不可。魂が宿るとされ、そのままゴミ出しは避ける考え方が一般的。",
    methodB: "状態の良い仏壇・経机はリユース店や骨董買取の対象になることがある。まずは査定を依頼。",
    methodC: "菩提寺のお焚き上げ、または遺品整理・供養業者に処分と供養をセットで依頼。魂抜き（閉眼供養）ののち処分する流れが一般的。",
    adviceFureai: "魂抜き（閉眼供養）が必要です。当センターなら提携のお坊さんや供養業者をご紹介できます。仏壇だけでなく、位牌・遺影・お仏具のまとめて供養もご相談ください。",
    memorialNote: "魂抜き・閉眼供養ののち、お焚き上げや寺院供養が一般的。故人・ご家族の意向を確認してから手続きを。",
    ctaType: "memorial",
  },
  {
    slug: "ihai",
    name: "位牌・仏具（おりん、経机、遺影）",
    categoryId: "memorial",
    gomiConclusion: "可燃",
    costNote: "寺院での供養・お焚き上げで数千円〜2万円程度。遺品整理業者にまとめて依頼する場合も。",
    canSell: false,
    methodA: "可燃ゴミで出せる自治体もあるが、位牌・遺影は「もの」としてではなく供養してから手放す方が望ましいとされる。",
    methodB: "位牌・仏具は買取対象になりにくい。供養を優先する選択が一般的。",
    methodC: "菩提寺や供養業者でお焚き上げ・供養を依頼。遺品整理業者なら仏壇とセットで引き取ってもらえる。",
    adviceFureai: "位牌や遺影は、ご家族の気持ちを大切にした供養がおすすめです。当センターでは、仏壇・位牌・遺影をまとめて供養できる提携業者をご案内しています。",
    memorialNote: "位牌は「魂が移ったもの」として、寺院での供養ののちお焚き上げや返却が一般的。",
    ctaType: "memorial",
  },
  {
    slug: "hinaningyo",
    name: "雛人形・五月人形",
    categoryId: "memorial",
    gomiConclusion: "粗大ゴミ",
    costNote: "供養込みで1体数千円〜2万円程度。まとめて供養すると割安になることが多い。",
    canSell: true,
    sellNote: "高級品・アンティークは買取対象になる場合あり。一般の市販品は買取不可が多い。",
    methodA: "自治体によっては「人形」を粗大ゴミで受け付ける。供養を希望しない場合は申し込み可能な地域も。",
    methodB: "雛人形・五月人形の買取は限定的。高級品は査定の価値あり。",
    methodC: "人形供養を行っている神社・寺院や人形供養業者に依頼。感謝の気持ちを込めて送る儀式ののち、お焚き上げやリサイクル。",
    adviceFureai: "「捨てる」ではなく「供養して送る」と気持ちが楽になる方が多いです。当センターでは、想い出の品の供養から実家全体の整理まで、一貫してご相談いただけます。",
    memorialNote: "人形供養ののち、お焚き上げやリサイクル。神社・寺院のほか、人形メーカーの供養イベントもある。",
    ctaType: "memorial",
  },
  {
    slug: "ningyo",
    name: "日本人形・フランス人形・ぬいぐるみ",
    categoryId: "memorial",
    gomiConclusion: "粗大ゴミ",
    costNote: "供養込みで1体数千円〜2万円程度。ぬいぐるみのみなら可燃で出せる地域も。",
    canSell: true,
    sellNote: "アンティーク人形は買取対象になる場合あり。ぬいぐるみは需要が限定的。",
    methodA: "人形は粗大ゴミ、小さなぬいぐるみは可燃ゴミで出せる自治体が多い。供養を希望する場合は専門業者へ。",
    methodB: "高級・アンティーク人形は古美術店などで買取の可能性。まずは査定を。",
    methodC: "人形供養の神社・寺院や供養業者に依頼。遺品整理業者でも人形の供養をセットで受けている。",
    adviceFureai: "長年大切にしてきた人形は、供養してから手放すと心が軽くなる方が多いです。実家の「想い出の品」をどうするか、一緒に整理の進め方からご相談できます。",
    memorialNote: "人形供養（感謝の気持ちを込めて送る儀式）ののち、お焚き上げやリサイクル。",
    ctaType: "memorial",
  },
  {
    slug: "shashin",
    name: "写真・アルバム",
    categoryId: "memorial",
    gomiConclusion: "可燃",
    costNote: "可燃ゴミで出せる。デジタル化業者に依頼する場合は1枚数十円〜数百円程度。",
    canSell: false,
    methodA: "可燃ゴミで処分可能（自治体のルールに従う）。そのまま捨てる前に、必要な分はスキャンやスマホ撮影で残す選択も。",
    methodB: "買取対象にはならない。デジタルデータ化してDVDやクラウドに残すサービスは有料で多数あり。",
    methodC: "大量の写真・アルバムをデジタル化する業者や、遺品整理で「選別・データ化」をセットで依頼する方法がある。",
    adviceFureai: "写真は「全部捨てる」より「残したい分だけデータ化してから手放す」と後悔が少ないです。実家の写真整理から、遺品整理全体の進め方までご相談ください。",
    ctaType: "memorial",
  },
  {
    slug: "kamidana",
    name: "神棚・お札・お守り",
    categoryId: "memorial",
    gomiConclusion: "可燃",
    costNote: "神社に納める場合は初穂料数千円程度。お札・お守りは神社の古札納め所へ持参すれば無料のことが多い。",
    canSell: false,
    methodA: "お札・お守りは神社の「古札納め所」へ。神棚は自治体により可燃または粗大ゴミ。丁寧に扱うなら神社に相談。",
    methodB: "買取対象にならない。",
    methodC: "神棚の撤去・お焚き上げを依頼できる神社や業者あり。遺品整理業者にまとめて相談も可。",
    adviceFureai: "神棚・お札は、感謝の気持ちを込めて神社に納めるのが一般的です。実家の神棚の扱いに迷ったら、地域の神社や当センターの提携業者にご相談を。",
    ctaType: "memorial",
  },
  {
    slug: "kimono",
    name: "着物・帯・和装小物",
    categoryId: "memorial",
    gomiConclusion: "可燃",
    costNote: "自治体の可燃ゴミで出せる（少量ずつ）。宅配買取・出張買取は無料のことが多い。",
    canSell: true,
    sellNote: "正絹・有名作家・保存状態が良いものは買取価格がつくことがある。まとめて査定してもらうと効率的。",
    methodA: "可燃ゴミで出せる自治体が多い（規定に従い少量ずつ）。その前に買取査定を検討する価値あり。",
    methodB: "着物買取専門店や宅配買取で査定を。正絹・ブランド・状態が良ければ高値がつく場合も。捨てるより売る選択を強く推奨。",
    methodC: "大量の着物は遺品整理・不用品回収業者にまとめて依頼。買取可能分は査定、不可分は処分。",
    adviceFureai: "着物は「まず買取査定」がおすすめです。高価なものは売却で処分費を相殺できることも。実家の着物が何点あるか、全体の整理と一緒に把握したい方は無料診断をご利用ください。",
    ctaType: "buy_sell",
  },
  {
    slug: "shoujo",
    name: "賞状・トロフィー・勲章",
    categoryId: "memorial",
    gomiConclusion: "可燃",
    costNote: "可燃ゴミで出せる。業者にまとめて処分を依頼する場合は遺品整理の一部として。",
    canSell: false,
    methodA: "賞状は可燃ゴミ。トロフィーは金属部分が不燃の自治体もあるため要確認。",
    methodB: "一般的な賞状・トロフィーは買取対象にならない。",
    methodC: "遺品整理業者に「想い出の品」として選別・処分を依頼できる。",
    adviceFureai: "写真に残してから処分する方も多いです。実家の賞状・トロフィーをどう残すか、遺品整理の進め方と一緒にご相談できます。",
    ctaType: "default",
  },
  // --- 大型家具 ---
  {
    slug: "futon",
    name: "布団・座布団・毛布",
    categoryId: "daily",
    gomiConclusion: "可燃",
    costNote: "可燃ゴミで出せる自治体が多い（指定袋・量のルール要確認）。大量の場合は業者に依頼すると定額のことも。",
    canSell: false,
    methodA: "可燃ゴミで出せる地域がほとんど。少量ずつ指定袋に入れて出す。",
    methodB: "一般的な布団・毛布は買取対象になりにくい。",
    methodC: "大量にある場合は不用品回収・遺品整理業者にまとめて依頼。宅内の片付けとセットで見積もりを。",
    adviceFureai: "布団は実家に何枚あるか把握しづらいものです。実家じまい力診断で「荷物の量」を可視化すると、布団の処分も全体計画に組み込みやすくなります。",
    ctaType: "default",
  },
  {
    slug: "tansu",
    name: "タンス・婚礼家具（桐箪笥など）",
    categoryId: "furniture",
    gomiConclusion: "粗大ゴミ",
    costNote: "粗大ゴミは1点あたり数百円〜数千円。引き取り業者なら無料〜数千円のことも。大型なので運び出しが大変。",
    canSell: true,
    sellNote: "桐箪笥・高級タンスは買取の需要あり。状態が良ければ買取業者やリユース店に相談を。",
    methodA: "自治体の粗大ゴミで申し込み。大型のため分解・運搬が大変。戸建ての階段などは業者の方が楽な場合も。",
    methodB: "桐箪笥・ブランド家具は買取対象になることがある。まずは査定を。",
    methodC: "不用品回収・遺品整理業者に依頼。運び出しから処分まで一括で依頼できる。",
    adviceFureai: "大きなタンスは運び出しだけで一苦労。実家の間取りや階段の有無で費用も変わります。当センターの無料診断で、タンスを含めた「家全体の片付け費用の目安」を把握できます。",
    ctaType: "default",
  },
  {
    slug: "bed",
    name: "ベッド・マットレス（介護用・ウォーター含む）",
    categoryId: "furniture",
    gomiConclusion: "粗大ゴミ",
    costNote: "1点あたり数百円〜3千円程度（自治体による）。介護用ベッドは業者回収が一般的。",
    canSell: false,
    methodA: "自治体の粗大ゴミ申し込みが基本。分解して指定のゴミ袋で出せる地域もある。",
    methodB: "一般的なベッド・マットレスは買取対象になりにくい。",
    methodC: "介護用ベッド・ウォーターベッドは業者回収が確実。遺品整理・不用品回収でまとめて依頼を。",
    adviceFureai: "介護用ベッドは自治体で受け付けていない地域もあります。実家に残った医療・介護用品の処分も、当センターの提携業者でまとめてご相談できます。",
    ctaType: "default",
  },
  {
    slug: "sofa",
    name: "ソファ（コーナーソファ・電動リクライニング）",
    categoryId: "furniture",
    gomiConclusion: "粗大ゴミ",
    costNote: "1点あたり数百円〜4千円程度。大型・電動は業者回収が現実的。",
    canSell: true,
    sellNote: "状態が良ければリユース・買取の対象になることがある。",
    methodA: "自治体の粗大ゴミ。大型ソファは分解が必要な場合や、回収不可の自治体もあるため要確認。",
    methodB: "中古家具買取・リユース店に相談。電動ソファも対象になる場合あり。",
    methodC: "不用品回収・遺品整理業者に依頼。運び出しから処分まで一括。",
    adviceFureai: "コーナーソファや電動ソファは運び出しが大変です。実家の玄関・階段の広さで業者選びも変わります。無料診断で家の状況を伝えると、適した業者をご案内できます。",
    ctaType: "default",
  },
  {
    slug: "shokkidana",
    name: "食器棚・サイドボード",
    categoryId: "furniture",
    gomiConclusion: "粗大ゴミ",
    costNote: "粗大ゴミで1点数百円〜3千円程度。業者なら無料回収のことも。",
    canSell: true,
    sellNote: "木製・状態が良ければ買取・リユースの対象になることがある。",
    methodA: "自治体の粗大ゴミで申し込み。",
    methodB: "中古家具の買取・リユース店に査定を依頼。",
    methodC: "不用品回収・遺品整理業者に依頼。",
    adviceFureai: "食器棚は中身の食器の処分とセットで考えるとスムーズです。実家の片付けを「どこから手をつけるか」迷ったら、無料診断で優先順位を一緒に整理できます。",
    ctaType: "default",
  },
  {
    slug: "gakushu-desk",
    name: "学習机",
    categoryId: "furniture",
    gomiConclusion: "粗大ゴミ",
    costNote: "粗大ゴミで1点数百円〜3千円程度。引き取り業者なら無料〜数千円のことも。",
    canSell: true,
    sellNote: "ブランド品・木製で状態が良ければ買取可能。無料回収の業者も多く、査定で買取になる場合あり。",
    methodA: "自治体の粗大ゴミ申し込みか、分解して可燃・不燃で出せる自治体も（要確認）。",
    methodB: "子ども用家具の買取・リユース店に相談。",
    methodC: "不用品回収・遺品整理業者に依頼。",
    adviceFureai: "学習机は実家に1台あるご家庭も多いです。他の家具とまとめて業者に依頼すると、1点あたりの負担が減ることも。実家じまい力診断で全体の荷物量を把握してみてください。",
    ctaType: "default",
  },
  {
    slug: "massage-chair",
    name: "マッサージチェア",
    categoryId: "furniture",
    gomiConclusion: "粗大ゴミ",
    costNote: "重量があるため自治体では高額になる場合も。業者回収で1〜2万円程度の相場。",
    canSell: true,
    sellNote: "状態が良ければ中古買取の対象になることがある。",
    methodA: "自治体の粗大ゴミで申し込み可能な地域が多いが、重量で料金が高くなることも。",
    methodB: "家電・マッサージチェアの買取業者に査定を依頼。",
    methodC: "不用品回収・遺品整理業者に依頼。重いため業者依頼が現実的。",
    adviceFureai: "マッサージチェアは運び出しが大変です。実家の階段・玄関の状況を伝えれば、対応可能な業者を当センターからご紹介できます。",
    ctaType: "default",
  },
  {
    slug: "hondana",
    name: "本棚",
    categoryId: "furniture",
    gomiConclusion: "粗大ゴミ",
    costNote: "粗大ゴミで1点数百円〜2千円程度。本の処分は別（可燃または古紙）。",
    canSell: true,
    sellNote: "木製・状態が良ければリユースの対象になることがある。",
    methodA: "自治体の粗大ゴミ。本は可燃または古紙回収で別途。",
    methodB: "中古家具の買取・リユース店に相談。",
    methodC: "不用品回収・遺品整理業者に依頼。本の処分とセットで見積もりを。",
    adviceFureai: "本棚と中身の本は、まとめて「本は買取・古紙、棚は粗大ゴミ or 業者」と計画すると進めやすいです。実家の本の量を無料診断で把握するのもおすすめです。",
    ctaType: "default",
  },
  // --- 家電・デジタル ---
  {
    slug: "reizouko",
    name: "冷蔵庫・冷凍庫",
    categoryId: "appliance",
    gomiConclusion: "NG",
    costNote: "家電リサイクル法の対象。リサイクル料金＋収集運搬料で数千円〜1万円程度。",
    canSell: false,
    methodA: "自治体の一般ゴミでは出せない。家電リサイクル法に基づき販売店または指定引き取り場所へ。",
    methodB: "中古で使える場合は買取・無料回収の業者あり。",
    methodC: "家電量販店の回収窓口や、家電リサイクル業者に依頼。遺品整理業者でも対応可能。",
    adviceFureai: "冷蔵庫は家電リサイクル法の手続きが必要です。実家の家電をまとめて処分する場合は、遺品整理業者に一括依頼すると手続きが楽になります。",
    ctaType: "default",
  },
  {
    slug: "sentakuki",
    name: "洗濯機・衣類乾燥機",
    categoryId: "appliance",
    gomiConclusion: "NG",
    costNote: "家電リサイクル法の対象。リサイクル料金＋収集運搬料で2千円〜5千円程度。",
    canSell: false,
    methodA: "自治体では出せない。家電リサイクル法に基づき販売店または指定場所へ。",
    methodB: "中古で使える場合は無料回収の業者もあり。",
    methodC: "家電量販店・家電リサイクル業者・遺品整理業者に依頼。",
    adviceFureai: "洗濯機も家電リサイクル法の対象です。実家の家電を一括で処分したい場合は、当センターの提携業者にまとめてご依頼いただけます。",
    ctaType: "default",
  },
  {
    slug: "tv",
    name: "テレビ（ブラウン管・液晶）",
    categoryId: "appliance",
    gomiConclusion: "NG",
    costNote: "家電リサイクル法の対象。リサイクル料金＋収集運搬料で2千円〜5千円程度（サイズによる）。",
    canSell: true,
    sellNote: "液晶・薄型は中古需要あり。無料回収＋買取の業者に相談を。",
    methodA: "自治体では出せない。家電リサイクル法に基づき販売店または指定場所へ。",
    methodB: "液晶・薄型は買取・無料回収の業者あり。",
    methodC: "家電量販店・家電リサイクル業者・遺品整理業者に依頼。",
    adviceFureai: "テレビはサイズで料金が変わります。実家の家電をまとめて処分する際は、見積もりでリサイクル料金を確認してから依頼するのがおすすめです。",
    ctaType: "default",
  },
  {
    slug: "eacon",
    name: "エアコン",
    categoryId: "appliance",
    gomiConclusion: "NG",
    costNote: "家電リサイクル法の対象。取り外し＋リサイクルで5千円〜1万円程度。",
    canSell: true,
    sellNote: "稼働するものは買取・下取りの対象になることがある。",
    methodA: "自治体では出せない。取り外し工事が必要なため、販売店や専門業者への依頼が前提。",
    methodB: "買い替え時に販売店の下取りを利用。単体処分なら家電リサイクル業者へ。",
    methodC: "取り外し＋回収をセットで依頼できる業者に依頼。遺品整理で家電一式を任せる場合も。",
    adviceFureai: "エアコンは取り外しが必須です。実家が空き家になる前に、エアコン・家電の処分を業者にまとめて依頼するケースが多くあります。",
    ctaType: "default",
  },
  {
    slug: "pasokon",
    name: "パソコン・ノートPC",
    categoryId: "appliance",
    gomiConclusion: "NG",
    costNote: "PCリサイクル法の対象（メーカー回収または自治体）。データ消去は別途有料のことも。",
    canSell: true,
    sellNote: "メーカー・型番によっては買取対象。データ消去を依頼する業者も多い。",
    methodA: "PCリサイクル法に基づきメーカー回収または自治体の回収へ。データ消去は自分で行うか業者に依頼。",
    methodB: "データ消去付き買取や下取りをしている業者あり。個人情報が心配な場合は消去証明付きの業者が安心。",
    methodC: "データ消去＋回収をセットで依頼できる業者に依頼。遺品整理でPC・デジタル機器をまとめて対応してもらう方法も。",
    adviceFureai: "パソコンはデータ消去の不安が大きい方も多いです。当センターのデジタル遺品リスク診断で、スマホ・PCの「見られたくないデータ」の扱いを整理するヒントになります。",
    ctaType: "default",
  },
  {
    slug: "kotatsu",
    name: "こたつ・電気カーペット",
    categoryId: "appliance",
    gomiConclusion: "粗大ゴミ",
    costNote: "粗大ゴミで1点数百円〜2千円程度。無料回収の業者も多い。",
    canSell: true,
    sellNote: "状態が良ければ中古買取の対象になることがある。",
    methodA: "自治体の粗大ゴミ。脚と布団を分けて出せる自治体もある。",
    methodB: "不用品買取・リユース店に相談。",
    methodC: "不用品回収業者に依頼。",
    adviceFureai: "こたつは実家に残りがちな品目の一つ。他の不用品とまとめて業者に依頼すると、実家全体の片付けが進みやすくなります。",
    ctaType: "default",
  },
  // --- 処理困難物 ---
  {
    slug: "kinko",
    name: "金庫（耐火金庫・業務用）",
    categoryId: "difficult",
    gomiConclusion: "NG",
    costNote: "自治体では回収できないことがほとんど。専門業者で1〜5万円程度。耐火金庫は高額になる場合も。",
    canSell: false,
    methodA: "自治体では回収できません。耐火金庫・大型金庫は特にNG。",
    methodB: "金庫は買取対象になりにくい。開錠・処分の専門業者へ。",
    methodC: "金庫の開錠・処分を請け負う専門業者に依頼。遺品整理業者でも「処理困難物対応」を掲げているところがある。",
    adviceFureai: "金庫は自治体では回収できません。専門業者が必要です。当センターでは、処理困難物に対応した片付け業者のマッチングもご案内しています。実家に金庫が残っている場合もご相談ください。",
    ctaType: "difficult",
  },
  {
    slug: "shoukaki",
    name: "消火器",
    categoryId: "difficult",
    gomiConclusion: "NG",
    costNote: "自治体の一般ゴミでは出せない。メーカー・販売店の回収や専門業者で数百円〜数千円程度。",
    canSell: false,
    methodA: "自治体では回収できません。中身が入ったままでは危険。",
    methodB: "買取対象にならない。",
    methodC: "消火器のメーカー・販売店の回収サービス、または不用品回収業者（消火器対応可）に依頼。",
    adviceFureai: "消火器はそのままゴミに出せません。実家の倉庫や車庫に残っている場合、処理困難物対応の業者にまとめて依頼するのがおすすめです。当センターから該当業者をご紹介できます。",
    ctaType: "difficult",
  },
  {
    slug: "piano",
    name: "ピアノ・エレクトーン",
    categoryId: "difficult",
    gomiConclusion: "NG",
    costNote: "処分（廃棄）は1〜3万円程度が相場。引き取り無料の業者もあるが条件あり。",
    canSell: true,
    sellNote: "アップライト・グランドともに、状態が良ければ買取・譲渡の需要あり。無料引き取り＋査定の業者に相談を。捨てるより売る・譲るを優先。",
    methodA: "自治体の粗大ゴミでは受け付けない場合がほとんど。ピアノは「処理困難物」に近い。",
    methodB: "ピアノ専門の引き取り・買取業者に相談。状態が良ければ買取または無料引き取りで譲渡先を探してくれる。",
    methodC: "ピアノ専門の廃棄・リサイクル業者に依頼。遺品整理業者でもピアノ対応をしているところがある。",
    adviceFureai: "ピアノは「まず買取・譲渡」を検討する価値が高いです。高価で売れる可能性があります。実家のピアノだけでなく、家全体の整理の進め方も無料診断でご相談ください。",
    ctaType: "buy_sell",
  },
  // --- 趣味・コレクション ---
  {
    slug: "chadougu",
    name: "茶道具・骨董品・掛け軸",
    categoryId: "hobby",
    gomiConclusion: "可燃",
    costNote: "骨董・美術品として買取査定が先。処分のみなら業者で有料回収のことも。",
    canSell: true,
    sellNote: "真贋・作者により高価買取の可能性。専門の骨董・茶道具買取業者に査定を。捨てるより売る提案を強化。",
    methodA: "可燃ゴミで出せるが、価値がある可能性があるため安易な廃棄はもったいない。まず査定を。",
    methodB: "茶道具・骨董・掛け軸は専門買取業者に査定を依頼。高額で売れる場合もある。",
    methodC: "買取不可と判断した分は、骨董・美術品の処分を扱う業者や遺品整理業者に依頼。",
    adviceFureai: "茶道具・骨董は「ゴミにするのはもったいない」と感じる方が多いです。まずは買取査定がおすすめ。実家にどんな品があるか、全体の整理と一緒に当センターの無料診断で把握できます。",
    ctaType: "buy_sell",
  },
  {
    slug: "gakki",
    name: "楽器（ギター、三味線、琴、バイオリンなど）",
    categoryId: "hobby",
    gomiConclusion: "粗大ゴミ",
    costNote: "自治体の粗大ゴミで出せる場合もあるが、高級品は買取価値あり。まず査定を。",
    canSell: true,
    sellNote: "ブランド・状態が良ければ楽器の買取需要あり。専門買取店に相談を。",
    methodA: "自治体の粗大ゴミで申し込み可能な地域が多い。ただし高価な楽器はもったいないので査定を優先。",
    methodB: "楽器の買取専門店やリユース店に査定を依頼。捨てるより売る選択を推奨。",
    methodC: "買取不可の場合は不用品回収・遺品整理業者に依頼。",
    adviceFureai: "楽器は買取需要が高い品目です。実家にギターや三味線が残っている場合、まず買取査定から始めるのがおすすめ。実家全体の片付け計画は無料診断で整理できます。",
    ctaType: "buy_sell",
  },
  {
    slug: "gorufu",
    name: "ゴルフセット・ゴルフバッグ",
    categoryId: "hobby",
    gomiConclusion: "粗大ゴミ",
    costNote: "粗大ゴミで出せる。クラブは金属で不燃扱いの自治体もある。買取なら無料のことが多い。",
    canSell: true,
    sellNote: "ブランド・型番によっては買取価格がつく。ゴルフ専門の買取店に相談を。",
    methodA: "自治体の粗大ゴミ。クラブとバッグで分別が必要な地域も。",
    methodB: "ゴルフクラブ・バッグの買取店に査定を依頼。捨てるより売る選択を。",
    methodC: "不用品回収業者に依頼。",
    adviceFureai: "ゴルフ道具は「まず買取」がお得です。実家の不用品のなかで、売れるものと捨てるものを分けるところから、当センターの診断で一緒に整理できます。",
    ctaType: "buy_sell",
  },
  // --- 日用品・大量 ---
  {
    slug: "shokki",
    name: "食器・陶器・グラス",
    categoryId: "daily",
    gomiConclusion: "不燃",
    costNote: "不燃ゴミで出せる自治体が多い。大量の場合は業者にまとめて依頼も。",
    canSell: true,
    sellNote: "ブランド食器・骨董的な陶器は買取の可能性あり。",
    methodA: "不燃ゴミで出せる地域がほとんど。割れないように新聞で包む等のルールを確認。",
    methodB: "ブランド食器・陶器は買取店に査定を依頼できる。",
    methodC: "大量の食器は遺品整理・不用品回収業者にまとめて依頼。",
    adviceFureai: "食器は実家にたくさん残りがちです。「使う人に譲る」「処分する」を分けると進めやすいです。実家じまい力診断で、食器を含めた荷物量の目安を把握できます。",
    ctaType: "default",
  },
  {
    slug: "irui",
    name: "衣類・古着（大量）",
    categoryId: "daily",
    gomiConclusion: "可燃",
    costNote: "可燃ゴミで出せる（少量ずつ）。大量の場合は古着回収や業者依頼が現実的。",
    canSell: true,
    sellNote: "ブランド・状態が良ければ古着買取の対象。まとめて宅配買取に出す方法も。",
    methodA: "可燃ゴミで出せる自治体が多い。大量の場合は指定袋の数・回数に注意。",
    methodB: "古着買取・宅配買取にまとめて出す。売れない分は処分。",
    methodC: "大量の衣類は遺品整理・不用品回収業者にまとめて依頼。",
    adviceFureai: "衣類は「残す・譲る・捨てる」の選別に時間がかかります。実家のクローゼットの量を把握したい方は、無料診断で全体の荷物量を可視化してみてください。",
    ctaType: "default",
  },
];

export function getDisposeItemBySlug(slug: string): DisposeItem | undefined {
  return DISPOSE_ITEMS.find((i) => i.slug === slug);
}

export function getDisposeSlugs(): string[] {
  return DISPOSE_ITEMS.map((i) => i.slug);
}

export function getItemsByCategoryId(categoryId: string): DisposeItem[] {
  return DISPOSE_ITEMS.filter((i) => i.categoryId === categoryId);
}
